name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build artifact
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Storing artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz
